//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenthDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dormitories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dormitories()
        {
            this.Rooms = new HashSet<Rooms>();
        }
    
        public int Hostel { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public byte[] Picture { get; set; }
        public string Owner { get; set; }
        public int RoomCount { get; set; }
        public int Beds { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rooms> Rooms { get; set; }
    }
}
