//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenthDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Living
    {
        public int ID { get; set; }
        public string Document { get; set; }
        public int LodgerID { get; set; }
        public int RoomID { get; set; }
        public System.DateTime Begin { get; set; }
        public string Giver { get; set; }
        public string Comment { get; set; }
        public decimal Payment { get; set; }
        public System.DateTime Settlement { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public string Reason { get; set; }
    
        public virtual Lodgers Lodgers { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
