//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenthDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lodgers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lodgers()
        {
            this.Living = new HashSet<Living>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Passport { get; set; }
        public System.DateTime PassportDate { get; set; }
        public string Region { get; set; }
        public string Work { get; set; }
        public bool Children { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Living> Living { get; set; }
    }
}
