//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenthDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rooms()
        {
            this.Living = new HashSet<Living>();
        }
    
        public int ID { get; set; }
        public double Square { get; set; }
        public string Comment { get; set; }
        public byte RoomBeds { get; set; }
        public int TypeID { get; set; }
        public byte Storey { get; set; }
        public int HosteID { get; set; }
        public int NumberInDormitory { get; set; }
    
        public virtual Dormitories Dormitories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Living> Living { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
